### ISSUE TITLE
audits for procurement

### ISSUE THREAD

**Issue by eins78** [leihs/leihs#1193]
* we want to implement it for completenes sake and consistency
* almost identical technical solution is needed for new borrow!

### tasks

- [ ] database: add auditing for `procurement_*` tables
- [x] backend/API: add support for auditing
  - [x] distinguish GraphQL operation types (only audit if doc contains a `mutation`)
  - [x] provide session/requestid/etc for the DB auditing

**Comment by nimaai** [comment]
part of https://github.com/leihs/leihs/issues/1450
