### ISSUE TITLE
ui: Confirmation and Alert dialogs

### ISSUE THREAD

**Issue by eins78** [leihs/leihs#1195]
* use new component `ConfirmDialog`  https://next.ui.leihs.app/?path=/story/mobileapp-design-components-layout-confirmdialog--show-confirm-and-alert
* naming of "Alert" and "Confirm" variant is supposed to be consistent with the DOM/JS methods, but can be renamed if there is a compelling proposal

#### tasks 

* [ ] #1178 
* [ ] confirm: "Cancel New Rental" (Warenkorb leeren)
* [ ] alert: "Submit Order" ("Order was submitted but still needs to be approved!")
* [ ] confirm & alert: "Cancel Rental" (Bestellung stornieren)
   do in separate task: #1175

#### deps

* [x] #1200
