### ISSUE TITLE
Admin: Optimize Admin UI

### ISSUE THREAD

**Issue by neoheat** [leihs/leihs#1620]
#### Goal 

According to design proposal
https://leihs-styleguide-mz9pu7gdx-leihs1.vercel.app/iframe.html?id=admin-layout--some-entity-page&viewMode=story

the goal is to optimize the UI / UX for the admin roles

#### Tasks Improvements to UI in Admin ( WIP ):

- [ ] draw and document processes for each role in admin UI
- [ ] design menu structure with separation for Inventory admin and Global admin functions
- [x] #1644
- [x] #1674
- [x] #1656
- [x] #1658
- [x] #1646
- [x] #1647
- [x] #1659
- [x] #1651
- [x] #1669
- [x] #1682
    - [x] #1683
    - [x] #1684
    - [x] #1685
    - [x] #1686
    - [x] #1687
    - [x] #1688
    - [x] #1689
    - [x] #1690
    - [x] #1691
    - [x] #1692
- [x] #1679
    - [x] #1680
    - [x] #1681
- [x] #1676
   - [x] #1678
   - [x] #1677
- [x] #1648
  - [x] #1667
  - [x] #1660
  - [x] #1657
  - [x] #1649
  - [x] #1650
  - [x] #1652
  - [x] #1653
  - [x] #1654
  - [x] #1655

to be considered
- [x] #1639

Tests & Review
- [x] #1698
- [x] #1699

#### Open questions

- decision to have a UI storybook for admin
- can the new admin UI be developed side by side to the existing admin UI?
- multi language frontend

**Comment by belafonte** [comment]
WIP Tasks List:

Improvements to UI in Admin:

- [ ] Add configurable Sidebar instead of Breadcrumps
- [ ] Remove Breadcrumps everywhere
- [ ] User one central component for filters
- [ ] Rework Inventory Pool Management
  - [ ] Remove Breadcrumps for navigation
  - [ ] Remove irritating Links ins Headers
  - [ ] In Users: Add "New User" from button instead of from "Role"
  - [ ] in Users Detail View: Add Groups
  - [ ] In Groups Detail View: Add Users of Groups to Group View, instead of in extra view
  - [ ] In Delegations Detail View: Use Tabs for Groups and Users
  - [ ] In Entitlement Groups Detail View: Use Tabs for Groups and Users

**Comment by belafonte** [comment]
https://github.com/leihs/leihs/commit/8770b381849df43efc9a388a6bae7563a08c4fd0
