### ISSUE TITLE
Admin: Move manage area into admin (Part 1 "Settings")

### ISSUE THREAD

**Issue by neoheat** [leihs/leihs#1724]
# **🚀 Feature Request**

## **Is your feature request related to a problem? Please describe.**
To be able to separate the role "inventory manager" from the tasks of managing the inventory pool settings, the manage area of `/manage/manage` shall be moved into `admin`.

The final goal is to implement a new role "inventory pool manager" who's responsible for the pool settings like opening hours, managing mail templates and individual data fields. Currently, the role "inventory manager" has access to these settings.

### Tasks of part 1

- [x] add new tabs `opening times` and `admin/inventory-pools/ `
- [x] move `Workdays ` and `Closed Days` in new tab `opening times`
- [x] move the following fields in existinig tab `settings`
  - textarea `Default Contract Note`
  - checkbox `Print Contracts`
  - checkbox `Automatic suspension`
  - textarea `Automatic suspension reason`
  - number `min. number of days... between handover`
  - checkbox `Handover Purpose`

**Comment by neoheat** [comment]
subtask tidy up database tables.
https://github.com/leihs/leihs/issues/1732

**Comment by nimaai** [comment]
https://github.com/leihs/leihs/commit/ac37a5dad19c9f2728ad96e39a1d6b3f03f96ccf
