### ISSUE TITLE
New inventory: test implementation of new techstack - inventory overview / search

### ISSUE THREAD

**Issue by neoheat** [leihs/leihs#1730]
# Task
Create a prototype app for inventory with the new evaluated tech stack according to results in #1671 and the mockups in https://www.figma.com/design/EsjbYu2EwXonUGkiC9W0NZ/Leihs---Inventory?m=dev&node-id=1703%3A5181&t=GIrlgssNbknfViLS-1

### Setup
- [x] Takeover prototype from #1671 
- [x] Setup of required Shadcn component
- [x] Tailwind Config
- [x] Setup Translations with i18next
- [x] setup mock data server
- [x] define routing and route parameters

### View list
- [x] create list view of inventory
- [x] refine components or style with tailwind
- [x] implement and style collapsible data row
- [x] filter evaluation (specific backend implementation or feasible directly)

### View modal/forms view
- [x] create view of forms within modal 
- [x] form validation / display errors and hints

### Data queries
- [x] define REST endpoints per view
