### ISSUE TITLE
Admin: Move manage area into admin (Part 2 "Inventory fields")

### ISSUE THREAD

**Issue by neoheat** [leihs/leihs#1735]
# **🚀 Feature Request**

## **Is your feature request related to a problem? Please describe.**
To be able to separate the role "inventory manager" from the tasks of managing the inventory pool settings, the manage area of /manage/manage shall be moved into admin.

The final goal is to implement a new role "inventory pool manager" who's responsible for the pool settings like opening hours, managing mail templates and individual data fields. Currently, the role "inventory manager" has access to these settings.

## **Describe the solution you'd like**

Managing the fields of an inventory park is currently done in the section `manage` of  an inventory pool. This should be moved into `admin`.

### Tasks of Part 2

- [ ] add new tab `Inventory Fields` in `admin/inventory-pools/`
- [ ] create list view of fields of the selected inventory pool
- [ ] create detail view of selected field with two separate views to edit properties `active`, `label` and field status per pool
- [ ] create form to edit `properties` or `field status by inventory pool` in modal window
- [ ] the form of `field status by inventory pool` should have an option to change the field status (active/inactive) for all at once.

### Mockups fields by inventory pool

![Leihs - Admin manage fields_list pool](https://github.com/leihs/leihs/assets/123965725/a4caa00a-ca39-4428-9812-d60f94b01a18)
![Leihs - Admin manage fields_edit pool](https://github.com/leihs/leihs/assets/123965725/c39d40cb-6b80-4c84-a58f-d2a6ec8e5fd5)

### Mockups "Global" fields

![Image](https://github.com/leihs/leihs/assets/123965725/6cff3c42-3b48-4d53-9a5b-6975cb8b8265)
![Image](https://github.com/leihs/leihs/assets/123965725/cedbb084-6395-4f46-8d9e-eb7c1583ebde)

**Comment by urs-van-binsbergen** [comment]
cb06f21418c80c9626685fe5427d62789de63b40
