### ISSUE TITLE
Admin: Move manage area into admin (Part 3 "Mail templates")

### ISSUE THREAD

**Issue by neoheat** [leihs/leihs#1760]
# **🚀 Feature Request**

## **Is your feature request related to a problem? Please describe.**
To be able to separate the role "inventory manager" from the tasks of managing the inventory pool settings, the manage area of /manage/manage shall be moved into admin.

The final goal is to implement a new role "inventory pool manager" who's responsible for the pool settings like opening hours, managing mail templates and individual data fields. Currently, the role "inventory manager" has access to these settings.

---

## **Describe the solution you'd like**

Managing the mail templates of an inventory park is currently done in the section `manage` of an inventory pool. This should be moved into admin.

### Tasks of Part 3

- [x] add new tab `Mail Templates` in  in `admin/inventory-pools/`
- [x] create list view incl. filters of mail templates of the selected inventory pool (same view as in global mail templates `admin/mail-templates/`)
- [x] create detail view of selected mail template (same view as in global mail templates `admin/mail-templates/{{UUID}}`
- [ ] edit form of mail template in modal window (with variables list in the right column)

## Mockups

![Image](https://github.com/user-attachments/assets/21058e43-ebe7-4a89-bf65-1588c543cdb3)

![Image](https://github.com/user-attachments/assets/a8b5f89e-f790-4c10-9679-749809c8caee)

![Image](https://github.com/user-attachments/assets/4e1f3972-6542-4f54-8954-f8e3321ca512)

**Comment by nimaai** [comment]
https://github.com/leihs/leihs/commit/8b4f61958cf46788a37f163dfde4ba14884e4d2f

**Comment by neoheat** [comment]
tested 👍
