### ISSUE TITLE
[Epic] Assign AccessRights/Roles via Groups

### ISSUE THREAD

**Issue by DrTom** [leihs/leihs#769]
https://github.com/leihs/leihs/issues/768 done
https://github.com/leihs/leihs/issues/767 done
https://github.com/leihs/leihs/issues/773 done

https://github.com/leihs/leihs/commit/f29c1aec6e90aa3178a93f7bb3233fbbdc938979

https://github.com/leihs/leihs/issues/805, fixed, broken on staging only
https://github.com/leihs/leihs/issues/808 fixed with different approach https://github.com/leihs/leihs/issues/819
https://github.com/leihs/leihs/issues/809 done
https://github.com/leihs/leihs/issues/810 fixed in https://github.com/leihs/leihs/issues/817
https://github.com/leihs/leihs/issues/811 done
https://github.com/leihs/leihs/issues/812 won't fix
https://github.com/leihs/leihs/issues/814 done
https://github.com/leihs/leihs/issues/816 done
https://github.com/leihs/leihs/issues/817 done
https://github.com/leihs/leihs/issues/818 done

https://github.com/leihs/leihs/commit/04368f2240c3daa45f4b4284ff0c3d20d4d0b660

**Comment by eins78** [comment]
Ziel: statt per Pool festzulegen "alle _neuen_ User haben automatisch Zugriffsrecht", sollen nur noch Gruppen verwendet werden.

Idee: neue Funktionalität parallel entwickeln, mit einem Pool ausprobieren, z.B. ITZ (weil dort eh keine/kaum Gegenstände als ausleihbar sind)

Anforderungen:
- Es muss möglich sein, einzelne User zu sperren #768 
- Änderungen an den Rechten der Gruppen (oder Zugehörigkeit der User zu diesen) muss jederzeit möglich sein, auch wenn gerade Reservationen oder Ausleihen aktiv sind
- Es muss möglich sein automatisch (sync) oder manuell erstellte Gruppen nebeneinander zu verwenden (z.B. wenn Gruppe der Inventarverwalter nicht im AD ist)
- Muss "inspectable" sein auf User-Profil (sichtbar ab Inventarverwalter aufwärts). Welche Rechte aufgrund welcher Gruppenzugehörigkeit.

**Comment by DrTom** [comment]
@eins78 closed war nehme ich an ein versehen

**Comment by eins78** [comment]
Nachfolge-Schritte:
- Delegationen anzeigen bei pool/user -> später
- Inventarverwalter kann Userverwaltung sehen -> Link vom alten UI aufs neue

**Comment by eins78** [comment]
- [x] im Admin Gruppenrechte verwalten
- [ ] letzte fixes (shared permissions query)
- [ ] legacy: bestehende "AccessRights" Modelle müssen angepasst werden
- [ ] my: "du hast keine rechte für nix" fehlerseite
- [ ] legacy: redirect-loop fixen, wenn keine Pool-rechte nach my weiterleiten

Delegationen: Berechtigungungen nach altem schema funktionieren immer noch, d.h. auch Delegationen gehen noch. Es können aber Gruppen und Delegation noch nicht vermischt werden.

**Comment by eins78** [comment]
Ergebnisse Besprechung:

1. admin app wird angepasst: Inventar- und lending manager bekommen zugriff auf den teil der userverwaltung um rollen zu sehen und zu bearbeiten.

2. admin-app userverwaltung aufhübschen, rollen besser anzeigen etc.

3. in legacy (user-liste im pool) wird die rolle nur noch lesend angezeigt, es gibt einen link zum admin-interface. @DrTom macht es grob, @eins78 hübscher.

4. Bugix: Keine Vergabe von Rechten die höher sind als die eigenen (auch nicht an sich selber!)

5. mittelfristig: konsequenter benennen "Gruppen" vs "Anspruchsgruppen". "Group Manager" ist auch verwirrend weil macht viel weniger als lending- und inventory m.

6. Delegationen: in legacy muss das alte Formular noch funktionieren. neue view soll unterscheiden zwischen "direkt roles" und "via groups". Für "direkt" Delegationen kann dann das Legacy interface zur Konfiguration verwendet werden.

**Comment by nadjaweisskopf** [comment]
Testing the ticket: 
Bug might have to do with this ticket? https://github.com/leihs/leihs/issues/805

**Comment by DrTom** [comment]
@nadjaweisskopf indirectly: #805 was probably indroduced before when preparing for this ticket. Anyways I assigend it to myself.

**Comment by nadjaweisskopf** [comment]
Can we change the following text: 
Instead of: "This section shows the roles aggregated from direct roles, and those via groups."
"These roles have either been assigned to the user directly or have been assigned to a group the user belongs to.

**Comment by DrTom** [comment]
Ich persönlich finde es nicht besser aber klar können wir ;-) Könntest du für jeden Task, auch diesen,  einfach ein neues Ticket anlegen? Man kann diese ganz oben verlinken.
